name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Prepare Jekyll
      run: sudo apt-get install jekyll

    - name: Build with Jekyll
      run: JEKYLL_ENV=production jekyll build
