name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Prepare 11ty (current)
      run: |
        sudo apt update
        sudo apt-get install nodejs npm

    - name: Install 11ty (current)
      run: npm install

    - name: Build with 11ty
      run: npm build
