name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Prepare Jekyll (current)
      run: |
        sudo apt update
        sudo apt-get install ruby-full build-essential zlib1g-dev
        echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
        echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc

    - name: Install Jekyll (current)
      run: sudo gem install jekyll bundler

    - name: Build with Jekyll
      run: JEKYLL_ENV=production jekyll build
